dist: bionic
language: python
group: travis_latest

before_script:
- gcc -v && g++ -v && cmake --version

install:
- pip install cmake

script:
- cmake -B build -Dbuild_tests:BOOL=on -DCMAKE_BUILD_TYPE=RelWithDebInfo
- cmake --build build

after_script:
- cd build
- ctest --output-on-failure
